# Generated by Django 2.0.1 on 2018-01-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userupload',
            name='physical_mailing_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userupload',
            name='receipt_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userupload',
            name='sent_confirmation_email',
            field=models.BooleanField(default=False),
        ),
    ]
