# Generated by Django 2.0.1 on 2018-01-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180128_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userupload',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='userupload',
            name='upload_image',
            field=models.ImageField(upload_to='user-uploads/%Y-%m-%d/'),
        ),
    ]
